---
title: "Mortality rate"
output:
  github_document
bibliography: Bibli.bib
csl: nature.csl
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align='center')
```

<details>
<summary>Packages</summary>
<p>

```{r}
want = c("dplyr",
         "stringr",
         "rmarkdown",
         "stats", 
         "tidyverse",
         "zoo", 
         "gganimate")

have = want %in% rownames(installed.packages())

# Install the packages that we miss
if ( any(!have) ) { install.packages( want[!have] ) }

# Load the packages
junk <- lapply(want, library, character.only = T)

# Remove the objects we created
rm(have, want, junk)

```
</details> 



# Introduction

# Mortality 

## Mortality rate projection

Regional projections of mortality for years 2016-2060.

(Source: [WHO](https://www.who.int/healthinfo/global_burden_disease/projections/en/) )

<details>
<summary>Codes</summary>
<p>

```{r echo=FALSE, message=FALSE, warning=FALSE}

sexe = c( "Male","Male","Male","Male","Male","Male","Female","Female","Female","Female","Female","Female","Male","Female")
age_grp = c(	"00-04",	"05-14",	"15-29",	"30-49",	"50-69",	"80",		"00-04",	"05-14",	"15-29",	"30-49",	"50-69",	"80","150","150")
Y2016 = c(0.00205,	0.00020,	0.00103,	0.00315,	0.01368,	0.06716,0.00174,	0.00015,	0.00042,	0.00131,	0.00643,	0.05791,1,1)

Y2030 = c(0.00127,	0.00016,	0.00079,	0.00266,	0.01076,	0.06051,	0.00108,	0.00012,	0.00034,	0.00118,	0.00588,	0.04796,1,1)

Y2045 = c(0.00087,	0.00013,	0.00074,	0.00203,	0.00902,	0.05864,	0.00075,	0.00010,	0.00030,	0.00092,	0.00514,	0.04965,1,1)

Y2060 = c(0.00065,	0.00012,	0.00067,	0.00188,	0.00714,	0.05645,	0.00057,	0.00009,	0.00027,	0.00084,	0.00440,	0.04833,1,1)

Mortality.rate.projection = data.frame(sexe,age_grp,Y2016, Y2030,Y2045,Y2060 )

```
</details> 


### Mortality rate projection for euro zone
```{r,echo= FALSE}
paged_table(Mortality.rate.projection)
```

<details>
<summary>Codes</summary>
<p>

### Percentage change
```{r, echo=FALSE, message=FALSE, warning=FALSE}

Mortality.rate.projection.age = Mortality.rate.projection %>% 
  filter(age_grp != "Total") %>%
  mutate(from = as.numeric(str_replace(string = age_grp,
            pattern = "(^\\d+).*",
            replacement = "\\1")),
         to = as.numeric(ifelse(nchar(age_grp) == 5,
                           substring(age_grp, 4,5),
                           from)),
         age = round((from+to)/2)) %>%
  group_by(sexe)  %>%
 complete(age = seq(min(age), max(age), by = 1))  %>%
  mutate(across(c(Y2016:Y2060), na.approx)) %>%
  select(!c(age_grp, from, to)) %>% 
  pivot_longer(!c(sexe, age), names_to = "Year", values_to = "Mortality_rate") %>% 
  mutate(Year = as.numeric(gsub("Y","",Year)))%>%
  group_by(sexe, age) %>% 
 complete(Year = seq(min(Year), max(Year), by = 1)) %>% 
  mutate(Mortality_rate = na.approx(Mortality_rate))


Mortality.rate.plot <- Mortality.rate.projection.age %>% 
  filter(age < 90) 

  
Mortality.rate.plot <- ggplot(subset(Mortality.rate.plot, sexe %in% "Male"), 
       aes(x = age,
           y = Mortality_rate,
           group = sexe,
           fill = sexe)) +
  geom_col(stat = 'identity',
           alpha = 0.4) +
   geom_col(data = subset(Mortality.rate.plot, sexe %in% "Female"), 
            aes(x = age,
           y = Mortality_rate,
           group = sexe,
           fill = sexe,
           stat = 'identity'),
           alpha = 0.4) +
   scale_fill_manual(values = c("#E7B800", "#00AFBB")) +
  scale_color_manual(values = c("#E7B800", "#00AFBB"))+
  theme_minimal() +
  ylab("") +
  xlab("age") +
  theme(legend.position="top")

Mortality.rate.plot <- Mortality.rate.plot + 
 labs(
      title = "Mortality Rate Projection\nin France\n\n{closest_state}",
      caption = "\n\nData Source: /www.who.int/healthinfo/global_burden_disease"
     )

Mortality.rate.plot <- Mortality.rate.plot +
  theme(axis.text = element_text(size = 14),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
       legend.key.size = unit(0.75, "cm"),
       legend.text = element_text(size = 15,face = "bold"),
       legend.title = element_blank(),
       plot.title = element_text(size = 22,hjust = 0.5,face = "bold"),
       plot.subtitle = element_text(size = 14, hjust = 0.5,face = "bold"),
       axis.title.x = element_text(size = 12,face = "bold"),
       plot.caption = element_text(size = 12, hjust = 0.5,face = "italic",color = "gray"))


Mortality.rate.plot <- Mortality.rate.plot + 
  transition_states(Year,
                    transition_length = 0.25,
                    state_length = 0.25) + 
  enter_fade() +
  exit_fade() + 
  ease_aes('cubic-in-out')

```
</details> 



```{r, echo =FALSE}
animate(Mortality.rate.plot,
        fps = 24,
        duration = 30,
        width = 500,
        height = 500,
        renderer = gifski_renderer("Mortality.rate.plot.gif"))
```

```{r, render=FALSE}

#brouillon

library(tidyverse)
library(glue)


Pop.proj = readRDS("Data/Pop.proj.rds") %>% 
  select(-age_grp.FACTOR) %>% 
  pivot_wider( names_from = year, values_from = Pop )
  
  
  
  filter(sexe == "Male" & year < 2010 & age < 3)

%>% 
  slice(rep(1:n(), each = 3)) %>% 
  group_by(year, sexe, age) %>% 
  mutate(id = row_number() - 1 + year)
  
  
  
  complete(TEST = seq(2007 , 2009,by = 1))
  
  
  
 # pivot_wider( names_from = year, values_from = Pop )
 # group_split(sexe, year) 







test =  data.frame(a = seq(2007,2050)) %>% 
  mutate(age = row_number()-1)

```

```{r, render= FALSE}
yy = grep("y2", colnames(Pop.proj))
yy
length(yy)


Pop.proj.male = Pop.proj %>%
  filter(sexe == "Male")
Pop.proj.female = Pop.proj %>%
  filter(sexe == "Female")

dim(Pop.proj)
dea = Pop.proj.male[,-ncol(Pop.proj.male)]; dim(dea)
yy = grep("y2", colnames(dea))
dea[,yy] = as.numeric(0)


max(dea$age)
for (A in 1:(nrow(dea)-1) ){ # index les num de colonnes
  for(Y in yy){ # indexe les années/colonnes
    dea[A, Y] = (Pop.proj.male[A, Y] - Pop.proj.male[A+1, Y+1]) / Pop.proj.male[A, Y]
  } # indexe les années/colonnes
} # index les num de colonnes
dea[nrow(dea), yy] = 1
plot( dea$age, dea$y2027)
```


# reference